

-- ENUMS

CREATE TYPE user_role_type AS ENUM ('user', 'admin');
CREATE TYPE expense_category AS ENUM ('need', 'want');

-- USER
CREATE TABLE IF NOT EXISTS "User" (
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   username VARCHAR(40) NOT NULL UNIQUE,
   email VARCHAR(254) NOT NULL UNIQUE,
   password VARCHAR(255),
   user_role user_role_type NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);


-- TASK
CREATE TABLE IF NOT EXISTS "Task" (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(70) NOT NULL,
    description VARCHAR(220),
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id INTEGER REFERENCES "User"(id)  ON DELETE CASCADE
);

-- EXPENSE
CREATE TABLE IF NOT EXISTS "Expense" (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(220),
    amount DECIMAL(12,2) NOT NULL,
    expense_type expense_category NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id INTEGER REFERENCES "User"(id)  ON DELETE CASCADE
);

-- TRAVEL
CREATE TABLE IF NOT EXISTS "Travel" (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(70) NOT NULL,
    description VARCHAR(200),
    milage INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id INTEGER REFERENCES "User"(id)  ON DELETE CASCADE
);